name: console_judge
description: Console based judge for competitive programming
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  dart_console: ^4.1.0
  args: ^2.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
